let data2 = {
      "nodes": [{'name': 'misfits'},
 {'name': 'mukachevo'},
 {'name': 'near_india_guild'},
 {'name': 'Move Capital'},
 {'name': 'afrikaburn'},
 {'name': 'arrozcriativo'},
 {'name': 'clan'},
 {'name': 'tb'},
 {'name': 'vitalpointai'},
 {'name': 'graffiti'},
 {'name': 'berryclub'},
 {'name': 'lisboa-hack'},
 {'name': 'nxm'},
 {'name': 'Ecosystem (KoG)'},
 {'name': 'wiki'},
 {'name': 'ceramic'},
 {'name': 'social-tokens'},
 {'name': 'Creatives'},
 {'name': 'motion'},
 {'name': 'rucommunity'},
 {'name': 'marmaj'},
 {'name': 'Community Squad'},
 {'name': 'portuguese'},
 {'name': 'kikimora'},
 {'name': 'marketing-vertical'},
 {'name': 'appalabs'},
 {'name': 'cura'},
 {'name': 'creatives'},
 {'name': 'curators'},
 {'name': 'incubadorapt'},
 {'name': 'neararabia'},
 {'name': 'zenbikers'},
 {'name': 'china_charity_dao'},
 {'name': 'san-francisco-near-hacknode'},
 {'name': 'turkey'},
 {'name': 'nft-onboarding'},
 {'name': 'muti'},
 {'name': 'hype'},
 {'name': 'Marketing Vertical'},
 {'name': 'Human Guild'},
 {'name': 'nearch4n'},
 {'name': 'degensdao'},
 {'name': 'dj-dao'},
 {'name': 'sandbox'},
 {'name': 'drops-dao'},
 {'name': 'bogotahacknode'},
 {'name': 'lisboa-node'},
 {'name': 'near_codame_china'},
 {'name': 'nearsamurai'},
 {'name': 'telegramcommunity'},
 {'name': 'move'},
 {'name': 'nyc'},
 {'name': 'art'},
 {'name': 'codame'},
 {'name': 'vietnam_covid19_charity'},
 {'name': 'nxm-dao'},
 {'name': 'Createbase'},
 {'name': 'vr-dao'},
 {'name': 'NxM'},
 {'name': 'npk-guild-nigeria'},
 {'name': 'cudo'},
 {'name': 'generative-art'},
 {'name': 'jusdao'},
 {'name': 'c1'},
 {'name': 'near-data-center'},
 {'name': 'indiacovidrelief'},
 {'name': 'createbase'},
 {'name': 'alas'},
 {'name': 'tamadao'},
 {'name': 'nft-gaming'},
 {'name': 'Genesis'},
 {'name': 'onboarding-dao'},
 {'name': 'near_asia_dev_dao'}],
  "links": 
  [{"target":"afrikaburn","source":"Community Squad","value":428.0},{"target":"alas","source":"NxM","value":0.0},{"target":"appalabs","source":"Human Guild","value":2500.0},{"target":"arrozcriativo","source":"Creatives","value":5581.0},{"target":"arrozcriativo","source":"NxM","value":38.0},{"target":"art","source":"Community Squad","value":2000.0},{"target":"art","source":"Human Guild","value":2000.0},{"target":"berryclub","source":"Createbase","value":150.0},{"target":"bogotahacknode","source":"Community Squad","value":560.0},{"target":"c1","source":"Creatives","value":3773.0},{"target":"ceramic","source":"Genesis","value":333.0},{"target":"china_charity_dao","source":"Community Squad","value":10000.0},{"target":"clan","source":"Creatives","value":340.0},{"target":"codame","source":"Createbase","value":5.0},{"target":"createbase","source":"Community Squad","value":300.0},{"target":"createbase","source":"Createbase","value":20.0},{"target":"createbase","source":"Creatives","value":7710.0},{"target":"creatives","source":"Community Squad","value":62434.0},{"target":"creatives","source":"Creatives","value":31190.58},{"target":"cudo","source":"Creatives","value":1657.0},{"target":"cura","source":"Creatives","value":620.0},{"target":"curators","source":"Community Squad","value":2100.0},{"target":"degensdao","source":"Ecosystem (KoG)","value":28900.0},{"target":"dj-dao","source":"Creatives","value":187.0},{"target":"dj-dao","source":"NxM","value":140.0},{"target":"drops-dao","source":"NxM","value":498.0},{"target":"generative-art","source":"Createbase","value":2000.0},{"target":"graffiti","source":"Createbase","value":200.0},{"target":"graffiti","source":"Creatives","value":156.0},{"target":"hype","source":"Creatives","value":3262.0},{"target":"incubadorapt","source":"Creatives","value":3158.0},{"target":"indiacovidrelief","source":"Createbase","value":10.0},{"target":"jusdao","source":"Createbase","value":8.0},{"target":"kikimora","source":"Human Guild","value":5000.0},{"target":"lisboa-hack","source":"Community Squad","value":1151.95},{"target":"lisboa-node","source":"Community Squad","value":913.0},{"target":"marketing-vertical","source":"Community Squad","value":20831.14},{"target":"marmaj","source":"Createbase","value":5.0},{"target":"marmaj","source":"Creatives","value":190.0},{"target":"marmaj","source":"Marketing Vertical","value":56.0},{"target":"misfits","source":"Community Squad","value":4142.0},{"target":"motion","source":"Creatives","value":889.44},{"target":"move","source":"Move Capital","value":48001.0},{"target":"mukachevo","source":"Community Squad","value":1885.0},{"target":"muti","source":"Creatives","value":2544.0},{"target":"muti","source":"NxM","value":170.0},{"target":"near-data-center","source":"Community Squad","value":1000.0},{"target":"near_asia_dev_dao","source":"Community Squad","value":710.0},{"target":"near_codame_china","source":"Createbase","value":200.0},{"target":"near_india_guild","source":"Community Squad","value":1943.5},{"target":"neararabia","source":"Community Squad","value":43.5},{"target":"neararabia","source":"Marketing Vertical","value":760.0},{"target":"nearch4n","source":"Creatives","value":600.0},{"target":"nearsamurai","source":"Community Squad","value":490.0},{"target":"nft-gaming","source":"Community Squad","value":2000.0},{"target":"nft-onboarding","source":"Community Squad","value":1005.0},{"target":"nft-onboarding","source":"Createbase","value":3050.0},{"target":"npk-guild-nigeria","source":"Community Squad","value":1367.5},{"target":"npk-guild-nigeria","source":"Marketing Vertical","value":1250.0},{"target":"nxm","source":"NxM","value":420.0},{"target":"nxm-dao","source":"Creatives","value":4205.0},{"target":"nxm-dao","source":"Marketing Vertical","value":140.0},{"target":"nyc","source":"Community Squad","value":1000.0},{"target":"onboarding-dao","source":"Creatives","value":263.0},{"target":"portuguese","source":"Community Squad","value":1395.0},{"target":"rucommunity","source":"Community Squad","value":5250.0},{"target":"rucommunity","source":"Marketing Vertical","value":1464.0},{"target":"san-francisco-near-hacknode","source":"Community Squad","value":700.0},{"target":"sandbox","source":"Community Squad","value":73271.0},{"target":"social-tokens","source":"Createbase","value":2000.0},{"target":"tamadao","source":"Human Guild","value":10000.0},{"target":"tb","source":"Createbase","value":120.0},{"target":"telegramcommunity","source":"Community Squad","value":1600.0},{"target":"turkey","source":"Marketing Vertical","value":280.0},{"target":"vietnam_covid19_charity","source":"Community Squad","value":10000.0},{"target":"vitalpointai","source":"Community Squad","value":6600.0},{"target":"vr-dao","source":"Community Squad","value":2000.0},{"target":"vr-dao","source":"Creatives","value":3083.0},{"target":"wiki","source":"Community Squad","value":4500.0},{"target":"zenbikers","source":"Creatives","value":728.0}]
  };